### ISSUE TITLE
Permission issues

### ISSUE THREAD

**Issue by unxplained** [linuxserver/docker-kasm#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/8056914/208362498-d205ccba-5485-4908-a0d6-523495940236.png)

![image](https://user-images.githubusercontent.com/8056914/208363206-84057027-f71e-4ea5-ba45-9498fc8751e7.png)

Got this weird image after clicking install

### Steps To Reproduce

1. Docker Desktop for m1 Mac

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

arm64

### Docker creation

```bash
---
version: "2.1"
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=443
      - TZ=Asia/Singapore
    volumes:
      - <path to directory>:/opt
    ports:
      - 3000:3000
      - 443:443
    restart: unless-stopped
```

### Container logs

```bash
time="2022-12-19T14:29:54+08:00" level=warning msg="containerd config version `1` has been deprecated and will be removed in containerd v2.0, please switch to version `2`, see https://github.com/containerd/containerd/blob/main/docs/PLUGINS.md#version-header"
time="2022-12-19T14:29:54.130296506+08:00" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
```

**Comment by thelamer** [comment]
I would assume it works without the volume mount (/opt) but this will be ephemeral. This container leverages DinD(docker in docker) to function and expects a sane Linux filesystem. I have not tested Docker Desktop(windows/mac), but try without the volume mount first as I would think that is what you are running into. 

As far as a solution I don't have many, I know most M1/2 devs usually leverage [Parallels](https://www.parallels.com/products/desktop/) Linux VM for a development environment as Docker Desktop is not ideal.

**Comment by sazonovanton** [comment]
Have a simular issue on x86_64. Except I wasn't able to get anything on 3000 or 443 ports.
Tried on two machines, exact same problem. Latest version of containerd

```
kasm  | [custom-init] No custom files found, skipping...
kasm  | [ls.io-init] done.
kasm  | time="2022-12-22T07:23:41Z" level=warning msg="containerd config version `1` has been deprecated and will be removed in containerd v2.0, please switch to version `2`, see https://github.com/containerd/containerd/blob/main/docs/PLUGINS.md#version-header"
kasm  | time="2022-12-22T07:23:41.089056990Z" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
```

**Comment by gkl1368** [comment]
I have the same problem on arm mac

**Comment by stedrow** [comment]
+1 to this issue, seeing the same thing on my arm mac as well with docker desktop.

**Comment by natewalck** [comment]
+1 to this issue on TrueNAS Scale (Debian based)

**Comment by j0nnymoe** [comment]
Closing issue as it was originally stated in the OP that the issue was for Mac and TheLamer gave a solution.

@natewalck no one within the team uses truenas scale but there is no reason why it shouldn't work providing you configure the permissions correctly.
