### ISSUE TITLE
[BUG] Running on Alpine gives an iptable error.

### ISSUE THREAD

**Issue by FrozenSource** [linuxserver/docker-kasm#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi guys,

Love your work as always and was now trying to setup Kasm using your docker-compose.
I have a server with only alpine and docker installed and have a policy of not hosting or modifying anything on the host other than the filesystem. As such I didn't touch anything related to networking or whatever. Docker containers do everything for me.

The error I am getting is related to iptables which I checked are active including the ipv6 one.

### Expected Behavior

I'd hope you guys can help with something I am missing here, it seems to be containerd related but could not find anything to resolve it.

### Steps To Reproduce

1. install alpine on a machine with docker.
2. create docker-compose.
3. docker-compose up.

### Environment

```markdown
- OS:Alpine
- How docker service was installed:apk
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.1"

services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=443
      - TZ=Europe/Amsterdam
#      - DOCKER_HUB_USERNAME=USER #optional
#      - DOCKER_HUB_PASSWORD=PASS #optional
    volumes:
      - ./data/opt:/opt
      - ./data/profiles:/profiles
#      - /dev/input:/dev/input #optional
#      - /run/udev/data:/run/udev/data #optional
    ports:
      - 3000:3000
      - 443:443
    restart: unless-stopped
```

### Container logs

```bash
kasm    | [custom-init] No custom services found, skipping...
kasm    | [migrations] started
kasm    | [migrations] no migrations found
kasm    | usermod: no changes
kasm    |
kasm    | -------------------------------------
kasm    |           _         ()
kasm    |          | |  ___   _    __
kasm    |          | | / __| | |  /  \
kasm    |          | | \__ \ | | | () |
kasm    |          |_| |___/ |_|  \__/
kasm    |
kasm    |
kasm    | Brought to you by linuxserver.io
kasm    | -------------------------------------
kasm    |
kasm    | To support LSIO projects visit:
kasm    | https://www.linuxserver.io/donate/
kasm    | -------------------------------------
kasm    | GID/UID
kasm    | -------------------------------------
kasm    |
kasm    | User uid:    911
kasm    | User gid:    911
kasm    | -------------------------------------
kasm    |
kasm    | [custom-init] No custom files found, skipping...
kasm    | [ls.io-init] done.
kasm    | time="2022-12-28T14:49:07+01:00" level=warning msg="containerd config version `1` has been deprecated and will be removed in containerd v2.0, please switch to version `2`, see https://github.com/containerd/containerd/blob/main/docs/PLUGINS.md#version-header"
kasm    | time="2022-12-28T14:49:07.194180895+01:00" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
kasm    | failed to start daemon: Error initializing network controller: Error creating default "bridge" network: Failed to Setup IP tables: Unable to enable NAT rule:  (iptables failed: iptables --wait -t nat -I POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE: iptables v1.8.7 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain POSTROUTING
kasm    |  (exit status 4))
kasm    | time="2022-12-28T14:49:08+01:00" level=warning msg="containerd config version `1` has been deprecated and will be removed in containerd v2.0, please switch to version `2`, see https://github.com/containerd/containerd/blob/main/docs/PLUGINS.md#version-header"
kasm    | time="2022-12-28T14:49:08.385522055+01:00" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
kasm    | failed to start daemon: Error initializing network controller: Error creating default "bridge" network: Failed to Setup IP tables: Unable to enable NAT rule:  (iptables failed: iptables --wait -t nat -I POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE: iptables v1.8.7 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain POSTROUTING
kasm    |  (exit status 4))
kasm    | time="2022-12-28T14:49:09+01:00" level=warning msg="containerd config version `1` has been deprecated and will be removed in containerd v2.0, please switch to version `2`, see https://github.com/containerd/containerd/blob/main/docs/PLUGINS.md#version-header"
kasm    | time="2022-12-28T14:49:09.753933113+01:00" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
kasm    | failed to start daemon: Error initializing network controller: Error creating default "bridge" network: Failed to Setup IP tables: Unable to enable NAT rule:  (iptables failed: iptables --wait -t nat -I POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE: iptables v1.8.7 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain POSTROUTING
kasm    |  (exit status 4))
kasm    | time="2022-12-28T14:49:11+01:00" level=warning msg="containerd config version `1` has been deprecated and will be removed in containerd v2.0, please switch to version `2`, see https://github.com/containerd/containerd/blob/main/docs/PLUGINS.md#version-header"
```

**Comment by thelamer** [comment]
I cannot replicate this, I installed Alpine 3.17.1. Post disk install (using setup-alpine) I ran: 

```
cat > /etc/apk/repositories << EOF; $(echo)
https://dl-cdn.alpinelinux.org/alpine/v$(cut -d'.' -f1,2 /etc/alpine-release)/main/
https://dl-cdn.alpinelinux.org/alpine/v$(cut -d'.' -f1,2 /etc/alpine-release)/community/
https://dl-cdn.alpinelinux.org/alpine/edge/testing/
EOF
apk add docker
```

Then ran the container: 
```
docker run --rm -it --privileged -p 3000:3000 -e KASM_PORT=443 -p 443:443 linuxserver/kasm:latest bash
```

I did not go too deep, but installed with the firefox container and launched it. Everything was functional for me. 

Did you install Alpine to disk or is this a live setup?

**Comment by FrozenSource** [comment]
Ok I did get a little further, I ran 3.16.... upgraded to "latest-stable" (giving me 3.17.1) and rebooted. Ran the container again (removing data). But now I get a processor tracer error. This happens for both my docker-compose as well as your command. Now I did look around to find a solution but most say it is just a warning. However, port 3000 doesn't do anything for me. It gives an empty response back.
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/14978036/216839744-eb4d342c-ff5b-4f9c-b5d8-2f381b253905.png">
I also changed the ports to test that. I don't run selinux or a firewall so that should not be it.

To answer your other question I run a disk install.

**Comment by thelamer** [comment]
You are correct that can be ignored, the DinD hack runs through some attempted settings to get the right FS etc before landing on the best performing one it can run. 

Though you are not dropping to a shell so something in init is not firing off correctly. When you run my command do we see this in your pstree:

```
ps -aef --forest                                                                                                                                                                                    
UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0  0 01:46 ?        00:00:00 /package/admin/s6/command/s6-svscan -d4 -- /run/service
root          14       1  0 01:46 pts/0    00:00:00 /bin/sh -e /run/s6/basedir/scripts/rc.init top bash
root         167      14  0 01:46 pts/0    00:00:00  \_ bash
root         422     167  0 01:47 pts/0    00:00:00      \_ ps -aef --forest
root          15       1  0 01:46 ?        00:00:00 s6-supervise s6-linux-init-shutdownd
root          16      15  0 01:46 ?        00:00:00  \_ /package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B
root          36       1  0 01:46 ?        00:00:00 s6-supervise s6rc-fdholder
root          37       1  0 01:46 ?        00:00:00 s6-supervise svc-kasm-wizard
root         140      37  0 01:46 ?        00:00:00  \_ bash ./run
root         335     140  0 01:46 ?        00:00:00      \_ /usr/bin/node index.js
root          38       1  0 01:46 ?        00:00:00 s6-supervise s6rc-oneshot-runner
root          47      38  0 01:46 ?        00:00:00  \_ /package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 3000
root          39       1  0 01:46 ?        00:00:00 s6-supervise svc-docker
root         141      39  0 01:46 ?        00:00:00  \_ docker-init -- dockerd --host=unix:///var/run/docker.sock -l error --data-root /opt/docker
root         213     141  0 01:46 ?        00:00:00      \_ dockerd --host=unix:///var/run/docker.sock -l error --data-root /opt/docker
root         233     213  0 01:46 ?        00:00:00          \_ containerd --config /var/run/docker/containerd/containerd.toml --log-level error
```

The only thing I could think of is a storage driver being used for Docker, though you said you installed via apk and made no mention to any runtime changes. Be default you should be getting overlay2 or fuse-overlayfs support.

**Comment by FrozenSource** [comment]
That was because it was the screen from docker-compose, here the one with the ps:
<img width="1886" alt="image" src="https://user-images.githubusercontent.com/14978036/216912220-aeefe46c-60cf-496f-8c06-3cac2fb1c2a4.png">

I also started to do a little of debugging. Apparently docker cannot connect to Containerd. I tried chmodding 777 to make sure I can access it which seems to have no effect.
<img width="1886" alt="image" src="https://user-images.githubusercontent.com/14978036/216915961-f7739a99-70fc-4a3d-8180-1ee9cde5c087.png">

Sorry I cannot get the logs raw..... my terminal is worthless and cannot get in in GitHub proper. I could not find any Containerd logs in the container..... nor any spec on enabling them.  These docker logs are by enabling them in the daemon.json:
{
  "debug": true
}

**Comment by thelamer** [comment]
@FrozenSource I dunno, it is tough without the ability to replicate locally and debug. 
Given I can do an Alpine 3.17.1 install and everything works for me we might be looking at something else with the underlying host. 
I specifically used virtualBox in Linux to test the Alpine install, I am assuming your deployment is bare metal or something else?

**Comment by FrozenSource** [comment]
It is on bare metal yeah.

**Comment by FrozenSource** [comment]
Funny thing is have also bare metal alpine on a pi3-arm64 got an iptables thing also... guess I just need a gnu install if I want this to work.
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/14978036/219151776-11707e19-085c-471c-8124-37ea6d2a06aa.png">
