### ISSUE TITLE
[BUG] Running Kasm on any other port than 443 behind Cloudflare Tunnels does not allow opening sessions

### ISSUE THREAD

**Issue by rursache** [linuxserver/docker-kasm#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently I have Kasm installed on port 18260 instead of the default 443. 

`https://LOCALIP:18260` works perfectly however my cloudflare tunnel `https://kasm.domain.tld` is not able to start any session

The Chrome console is full of errors because Kasm is trying to open `https://kasm.domain.tld:18260` instead of `https://kasm.domain.tld`

### Expected Behavior

The remote (cloudflare url) should work 1:1 as the local one

### Steps To Reproduce

1. Execute the docker run command below
2. Map the cloudflare tunnel to your domain
3. Test it

### Environment

```markdown
- OS: Ubuntu 22.04.2 LTS x86_64
- How docker service was installed: via the official install script
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
  --name kasm \
  --restart unless-stopped \
  --privileged \
  -p 18260:18260 \
  -p 18261:3000 \
  -e KASM_PORT=18260 \
  -e DOCKER_HUB_USERNAME="EMAIL" \
  -e DOCKER_HUB_PASSWORD="PASS" \
  -v /home/radu/.kasm/data:/opt \
  -v /home/radu/.kasm/profiles:/profiles \
  -v /dev/input:/dev/input \
  -v /run/udev/data:/run/udev/data \
  lscr.io/linuxserver/kasm:latest
```

### Container logs

```bash
https://pastebin.com/8kEZjYXS
```

**Comment by rursache** [comment]
Forgot to add, I'm not sure if this is a lsio issue or a Kasm issue, if it's not on you guys let me know and i'll move it to them. Thanks!

**Comment by thelamer** [comment]
This is a Kasm thing you need to set your proxy port to 0 in the guide here, then it absorbs it from whatever the current url scheme is https://www.kasmweb.com/docs/latest/how_to/reverse_proxy.html#update-zones

I need to whip up a swag reverse proxy conf and add this in the readme as you are not the first person to stumble on this, please don't close this issue so I remember.

**Comment by rursache** [comment]
Thank you @thelamer, setting `Proxy Port` to `0` in Kasm - Admin - Zones - default zone (edit) fixed it for me!

**Comment by thelamer** [comment]
This is now docced in the readme
