### ISSUE TITLE
[FEAT] rclone docker plugin

### ISSUE THREAD

**Issue by echo-devnull** [linuxserver/docker-kasm#37]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would like to request the addition of the docker rclone plugin inside this Docker-in-Docker setup. (https://rclone.org/docker/)

When I tried manually it fails since it needs specific folders, which in turn would need to be existing after restart as well.

### Reason for change

This would enable the use of KASM storage mappings: https://www.kasmweb.com/docs/latest/guide/storage_mappings.html

In particular, I'd like to use it with my linuxserver.io/nextcloud ;-)

### Proposed code change

Perhaps a simple startup command to install the plugin and added volume mappings in the docker compose file for it?

Or maybe even as a docker mod, so other projects might benefit as well?

**Comment by thelamer** [comment]
Both Rclone and the webcam support are specifically not included in this All in one image. For those features you would need to use a Native Kasm installation.

**Comment by johncadengo** [comment]
@echo-devnull were you ever able to make this work?

**Comment by gitwittidbit** [comment]
Hi, is there a reason why these two features (and particularly the rclone plugin) are not included? 

Not being able to mount cloud storage into containers on a per user basis substantially diminishes the value of the linuxserver.io installation compared to a native installation. Maybe there is a reason for this and I would love to know it.

Is it possible for me to add these plugins myself?

Thanks!

**Comment by thelamer** [comment]
`Hi, is there a reason why these two features (and particularly the rclone plugin) are not included?`
Yes they have underlying host dependencies, rclone needs fuse3 installed on the host and enabled in the kernel.
The webcam is just basically impossible in a DinD setup it needs to use v4l2loopback kernel module to make virtual webcams. An upcoming plugin will allow network egress rules like VPNs to be attached to workspaces again needs a special host thing in the form of IPtables control.

All of them can absolutely be possible but there is no way to automate it without the user following instructions and adding even heavier perms to the container to allow modprobe. Keep in mind we support Unraid users, Synology users, Truenas users, etc, etc. All of these users would be walled out from this as they cannot make these changes to their underlying host. 

For the users that have a real Linux box and want these features than do not use the all in one DinD container and do the native Kasm install. This container will stick to working as a container and not pollute the underlying host.

**Comment by gitwittidbit** [comment]
Thank you for the explanation.

I have tried using the native installer on a new VM but it doesn't seem to like my rootless docker there. Does it need to be installed with rootful docker or is there a way to install it using rootless docker?
