### ISSUE TITLE
arm64v8 image issues

### ISSUE THREAD

**Issue by shandshellin** [linuxserver/docker-kasm#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

unable to spin up container using :latest image for arm64v8. Can someone provide a specific tage to a known working imager version for amr64?

### Expected Behavior

Should determine the correct architecture automatically and grab the image.

### Steps To Reproduce

1. create service using :latest image
2. watch it fail repeatedly

### Environment

```markdown
- OS: Debian
- How docker service was installed: installed in the usual way as per the docker page, works for every other arm64 image i use
```

### CPU architecture

arm64

### Docker creation

```bash
created manually in portainer not with compose.
```

### Container logs

```bash
no logs as it doesn't spin up enough to create any logs
```

**Comment by Roxedus** [comment]
How can you say its failing, if you cant prove it with logs?

**Comment by j0nnymoe** [comment]
Provide us logs/errors that shows the image doesn't work.

**Comment by shandshellin** [comment]
no logs are created because it can't fire up the image to do so. Is there a specific tag i need to use to specify arm64 image? Seems like it is getting a non arm image.

**Comment by Roxedus** [comment]
no, there is not another tag you need to use.

**Comment by j0nnymoe** [comment]
You must be getting -some- error when creating as if the image didn't work for arm64, it would error out at creation.

**Comment by shandshellin** [comment]
can i specify an arm64 image for an older version? arm64v8-1.14.0 or something to force it?

**Comment by shandshellin** [comment]
will this image run in non-privilaged mode? That could be party of the hangup.

**Comment by j0nnymoe** [comment]
privilaged mode is required.

**Comment by Roxedus** [comment]
> requires being run in privileged mode
Pulling a specific tag would not solve the root cause, which we are very interested in figuring out. What *exactly* happens when you run it?
