### ISSUE TITLE
Login failed, kasm_api restarts every ~30 seconds

### ISSUE THREAD

**Issue by jeffreywyman** [linuxserver/docker-kasm#5]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

The installation looks good, I was able to install and it appears that all services are running smoothly, except kasm_api which restarts every minute.

When attempting to login to the Kasm Workspaces login page, it says "Login Failed" when using correct password set in initial setup.

------------------------------

## Expected Behavior

Login should work.

## Current Behavior

Login fails.

## Steps to Reproduce

1. Install Kasm
2. Set admin@kasm.local and user password
3. Select services and install
4. Try to login

## Environment
**OS:** 
Unraid 
**CPU architecture:** x86_64/arm32/arm64
	Xeon® E3-1225 v3
**How docker service was installed:**

https://github.com/orgs/linuxserver/packages/container/package/kasm
## Command used to create docker container (run/create/compose/screenshot)

Installed via community apps page
## Docker logs

text  error  warn  system  array  login  

time="2022-08-07T15:52:00.130397080-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T15:52:00.130572316-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=5798 runtime=io.containerd.runc.v2
time="2022-08-07T15:53:01.414419917-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T15:53:01.414484077-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T15:53:01.414494930-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T15:53:01.414728137-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=6064 runtime=io.containerd.runc.v2
time="2022-08-07T15:54:02.583383699-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T15:54:02.583441463-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T15:54:02.583524148-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T15:54:02.583682708-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=6290 runtime=io.containerd.runc.v2
time="2022-08-07T15:55:03.891822164-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T15:55:03.891878735-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T15:55:03.891889919-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T15:55:03.892047774-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=6517 runtime=io.containerd.runc.v2
time="2022-08-07T15:56:05.201372299-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T15:56:05.201438211-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T15:56:05.201450485-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T15:56:05.201670494-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=6742 runtime=io.containerd.runc.v2
time="2022-08-07T15:57:06.506843032-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T15:57:06.506914154-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T15:57:06.506926552-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T15:57:06.507100246-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=7148 runtime=io.containerd.runc.v2
time="2022-08-07T15:58:07.882699874-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T15:58:07.882766672-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T15:58:07.882777222-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T15:58:07.882932576-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=7446 runtime=io.containerd.runc.v2
time="2022-08-07T15:59:09.458316073-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T15:59:09.458389332-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T15:59:09.458402651-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T15:59:09.458607235-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=7668 runtime=io.containerd.runc.v2
time="2022-08-07T16:00:10.965725172-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T16:00:10.965787140-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T16:00:10.965798080-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T16:00:10.966042314-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=8536 runtime=io.containerd.runc.v2
time="2022-08-07T16:01:12.535963731-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T16:01:12.536026740-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T16:01:12.536038178-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T16:01:12.536209047-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=8852 runtime=io.containerd.runc.v2
time="2022-08-07T16:02:13.820082166-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T16:02:13.820170648-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T16:02:13.820186005-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T16:02:13.820356611-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=9077 runtime=io.containerd.runc.v2
time="2022-08-07T16:03:15.169064736-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T16:03:15.169149268-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T16:03:15.169173828-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T16:03:15.169336271-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=9417 runtime=io.containerd.runc.v2
time="2022-08-07T16:04:16.458932058-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T16:04:16.458994025-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T16:04:16.459005217-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T16:04:16.459156075-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=9640 runtime=io.containerd.runc.v2
time="2022-08-07T16:05:17.956349333-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T16:05:17.956402798-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T16:05:17.956412901-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T16:05:17.956606766-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=9996 runtime=io.containerd.runc.v2
time="2022-08-07T16:06:19.365525213-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T16:06:19.365594097-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T16:06:19.365605843-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T16:06:19.365925153-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=10641 runtime=io.containerd.runc.v2
time="2022-08-07T16:07:21.292996148-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T16:07:21.293057985-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T16:07:21.293086999-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T16:07:21.293262668-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=11006 runtime=io.containerd.runc.v2
time="2022-08-07T16:08:22.788338613-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T16:08:22.788394073-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T16:08:22.788408900-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T16:08:22.788579358-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=11222 runtime=io.containerd.runc.v2
time="2022-08-07T16:09:24.083009931-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T16:09:24.083074028-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T16:09:24.083141010-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T16:09:24.083355827-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=11745 runtime=io.containerd.runc.v2
time="2022-08-07T16:10:25.436361394-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T16:10:25.436423502-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T16:10:25.436471751-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T16:10:25.436673767-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=11993 runtime=io.containerd.runc.v2
time="2022-08-07T16:11:26.583664683-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T16:11:26.583744452-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T16:11:26.583755631-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T16:11:26.583915260-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=12327 runtime=io.containerd.runc.v2
time="2022-08-07T16:12:27.906151740-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T16:12:27.906218418-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T16:12:27.906230812-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T16:12:27.906395815-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=12887 runtime=io.containerd.runc.v2
time="2022-08-07T16:13:29.216700909-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T16:13:29.216760233-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T16:13:29.216770848-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T16:13:29.216925597-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=13168 runtime=io.containerd.runc.v2
time="2022-08-07T16:14:30.750446201-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2022-08-07T16:14:30.750501223-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2022-08-07T16:14:30.750514810-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2022-08-07T16:14:30.750782094-04:00" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/824c9cb5001270e0a59266bb17a81cf81010ad422df7407d915eb4b45f68ecf4 pid=13401 runtime=io.containerd.runc.v2

**Comment by thelamer** [comment]
Can you do me a favor and let me know the mount point you have set for `/opt` ? DinD will only function properly if this is mounted to a real disk like `cache` or `disk1`.

**Comment by jeffreywyman** [comment]
wow I can't believe I missed that. changed to cache and that worked, thank
you!
